### ISSUE TITLE
Negative language probability

### ISSUE THREAD

**Issue by whitelessk** [patrickschur/language-detection#20]
I try to improve language detection and set separate folder with samples as mentioned
```
$t = new LanguageDetection\Trainer();
$t->setMaxNgrams(9000);
$t->learn(/project/language/samples');
```
So it created json files in language directories
But when I try to detect language:
```
$ld = new LanguageDetection\Language([],/project/language/samples');
$ld->detect('some text here')->close()
```
I got negative probability
```
[
     "bg" => -0.63268817204301,
     "ru" => -1.183311827957,
 ]
```
So if used bestResults(), the wrong language code returns. Text in my case is russian.

Is it normal that negative probability is returned?

**Comment by patrickschur** [comment]
This is definetly not normal. How does your sample folder look like? Does it have the exact same structure like the resources folder in the repo?

**Comment by whitelessk** [comment]
@patrickschur the samples folder looks like
 samples
    ├── bg
    │   ├── bg.json
    │   └── bg.txt
    └── ru
        ├── ru.json
        └── ru.txt

seems that structure is the same as the resources folder
I can provide language samples or json results if it can help.

**Comment by whitelessk** [comment]
resolved the issue with setting $ld->setMaxNgrams(9000)

```
$ld = new LanguageDetection\Language([],/project/language/samples');
**$ld->setMaxNgrams(9000);**
$ld->detect('some text here')->close();
```
not sure why but if I learned library with 
`$t->setMaxNgrams(9000);`
so should use the same Ngrams with language detection
`$ld->setMaxNgrams(9000);`
otherwise negative probability returns

**Comment by satelliter** [comment]
I also encountered the same problem.

the test text is '식사를 마친 사람'
return:
object(LanguageDetection\LanguageResult)#7 (1) {
  ["result":"LanguageDetection\LanguageResult":private]=>
  array(7) {
    ["en"]=>
    int(0)
    ["ja"]=>
    int(0)
    ["ms-Latn"]=>
    int(0)
    ["th"]=>
    int(0)
    ["vi"]=>
    int(0)
    ["zh-Hant"]=>
    int(0)
    ["ko"]=>
    float(-0.51514726507714)
  }
}

Korean is correct, but the return is negative？

**Comment by patrickschur** [comment]
@whitelessk Nice to see, you solved your problem yourself. You have to specify the number of ngrams because the number is needed for calculating the confidence value of any language. 
@satelliter Does the problem still exists? Have you tried the solution from @whitelessk already?

**Comment by satelliter** [comment]
> @whitelessk Nice to see, you solved your problem yourself. You have to specify the number of ngrams because the number is needed for calculating the confidence value of any language.
> 
> @satelliter Does the problem still exists? Have you tried the solution from @whitelessk already?

My problem has been solved with his method, thank you！
